filebeat.config:
  modules:
    path: /usr/share/filebeat/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'

filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/nginx/access.log
#      - /usr/share/filebeat/logs/nginx/error.log
    fields:
      nginx: true
    fields_under_root: true
#  - type: log
#    paths:
#      - /usr/share/filebeat/logs/app/app.log
#    fields_under_root: true
output:
  logstash:
    hosts: ["192.168.15.7:5044"]
