- path: /
  method: GET
  resource: IndexController
  action: test

- path: /api/v1/groups
  method: POST
  resource: GroupController
  action: create

- path: /api/v1/groups/{group_id:number}
  method: GET
  resource: GroupController
  action: search

- path: /api/v1/groups/{group_id:number}
  method: PATCH
  resource: GroupController
  action: update

- path: /api/v1/groups/{group_id:number}
  method: DELETE
  resource: GroupController
  action: delete

- path: /api/v1/students
  method: POST
  resource: StudentController
  action: create

- path: /api/v1/students/{student_id:number}
  method: GET
  resource: StudentController
  action: search

- path: /api/v1/students/{student_id:number}/groups
  method: GET
  resource: StudentController
  action: searchGroups

- path: /api/v1/students/{student_id:number}
  method: PATCH
  resource: StudentController
  action: update

- path: /api/v1/students/{student_id:number}
  method: DELETE
  resource: StudentController
  action: delete

- path: /api/v1/teachers
  method: POST
  resource: TeacherController
  action: create

- path: /api/v1/teachers/{teacher_id:number}
  method: GET
  resource: TeacherController
  action: search

- path: /api/v1/teachers/{teacher_id:number}/groups
  method: GET
  resource: TeacherController
  action: searchGroups

- path: /api/v1/teachers/{teacher_id:number}
  method: PATCH
  resource: TeacherController
  action: update

- path: /api/v1/teachers/{teacher_id:number}
  method: DELETE
  resource: TeacherController
  action: delete

- path: /api/v1/requests/{request_id:number}
  method: GET
  resource: RequestController
  action: getStatus

- path: /api/v1/student/{student_id:number}/find-group
  method: POST
  resource: StudentController
  action: findGroup

- path: /api/v1/teacher/{teacher_id:number}/find-group
  method: POST
  resource: TeacherController
  action: findGroup

- path: /api/v1/group/{group_id:number}/find-teacher
  method: POST
  resource: GroupController
  action: findTeacher

- path: /api/v1/group/{group_id:number}/change-teacher
  method:  PATCH
  resource: GroupController
  action: changeTeacher

- path: /api/v1/group/{group_id:number}/form-group
  method:  POST
  resource: GroupController
  action: formGroup

- path: /api/v1/documentation/generate
  method: GET
  resource: DocumentationController
  action: generateDocumentation