- path: /
  method: GET
  resource: IndexController
  action: index

- path: /api/v1/group
  method: POST
  resource: GroupController
  action: create

- path: /api/v1/group
  method: GET
  resource: GroupController
  action: search

- path: /api/v1/group/{group_id:number}
  method: PATCH
  resource: GroupController
  action: update

- path: /api/v1/group/{group_id:number}
  method: DELETE
  resource: GroupController
  action: delete

- path: /api/v1/student
  method: POST
  resource: StudentController
  action: create

- path: /api/v1/student
  method: GET
  resource: StudentController
  action: search

- path: /api/v1/student/{student_id:number}
  method: PATCH
  resource: StudentController
  action: update

- path: /api/v1/student/{student_id:number}
  method: DELETE
  resource: StudentController
  action: delete

- path: /api/v1/teacher
  method: POST
  resource: TeacherController
  action: create

- path: /api/v1/teacher
  method: GET
  resource: TeacherController
  action: search

- path: /api/v1/teacher/{teacher_id:number}
  method: PATCH
  resource: TeacherController
  action: update

- path: /api/v1/teacher/{teacher_id:number}
  method: DELETE
  resource: TeacherController
  action: delete